-- MySQL Script generated by MySQL Workbench
-- mar 13 oct 2015 18:45:18 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OutGuat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OutGuat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OutGuat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `OutGuat` ;

-- -----------------------------------------------------
-- Table `OutGuat`.`TipoEstablecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`TipoEstablecimiento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(128) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`Establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`Establecimiento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idTipoEstablecimiento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Establecimiento_TipoEstablecimiento_idx` (`idTipoEstablecimiento` ASC)  COMMENT '',
  CONSTRAINT `fk_Establecimiento_TipoEstablecimiento`
    FOREIGN KEY (`idTipoEstablecimiento`)
    REFERENCES `OutGuat`.`TipoEstablecimiento` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`Atributo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`Atributo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(128) NOT NULL COMMENT '',
  `dimension` TINYINT(4) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`Valor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`Valor` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `valor` VARCHAR(128) NOT NULL COMMENT '',
  `idEstablecimiento` INT NOT NULL COMMENT '',
  `idAtributo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Valor_Establecimiento1_idx` (`idEstablecimiento` ASC)  COMMENT '',
  INDEX `fk_Valor_Atributo1_idx` (`idAtributo` ASC)  COMMENT '',
  CONSTRAINT `fk_Valor_Establecimiento1`
    FOREIGN KEY (`idEstablecimiento`)
    REFERENCES `OutGuat`.`Establecimiento` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Valor_Atributo1`
    FOREIGN KEY (`idAtributo`)
    REFERENCES `OutGuat`.`Atributo` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`Servicio` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(128) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`TipoUsuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idTipoUsuario` INT NOT NULL COMMENT '',
  `usuario` VARCHAR(45) NOT NULL COMMENT '',
  `nombre` VARCHAR(128) NULL COMMENT '',
  `fechaNacimiento` DATE NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `genero` TINYINT(4) NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Usuario_TipoUsuario1_idx` (`idTipoUsuario` ASC)  COMMENT '',
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `OutGuat`.`TipoUsuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`Reserva` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fechaInicio` DATETIME NOT NULL COMMENT '',
  `fechaFin` DATETIME NULL COMMENT '',
  `idValor` INT NOT NULL COMMENT '',
  `idUsuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Reserva_Valor1_idx` (`idValor` ASC)  COMMENT '',
  INDEX `fk_Reserva_Usuario1_idx` (`idUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Reserva_Valor1`
    FOREIGN KEY (`idValor`)
    REFERENCES `OutGuat`.`Valor` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `OutGuat`.`Usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`EstablecimientoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`EstablecimientoServicio` (
  `idServicio` INT NOT NULL COMMENT '',
  `idEstablecimiento` INT NOT NULL COMMENT '',
  `porcentaje` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idServicio`, `idEstablecimiento`)  COMMENT '',
  INDEX `fk_EstablecimientoServicio_Establecimiento1_idx` (`idEstablecimiento` ASC)  COMMENT '',
  CONSTRAINT `fk_EstablecimientoServicio_Servicio1`
    FOREIGN KEY (`idServicio`)
    REFERENCES `OutGuat`.`Servicio` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EstablecimientoServicio_Establecimiento1`
    FOREIGN KEY (`idEstablecimiento`)
    REFERENCES `OutGuat`.`Establecimiento` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`Calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OutGuat`.`Calificacion` (
  `idEstablecimiento` INT NOT NULL COMMENT '',
  `idServicio` INT NOT NULL COMMENT '',
  `idUsuario` INT NOT NULL COMMENT '',
  `punteo` MEDIUMINT(9) NULL COMMENT '',
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idEstablecimiento`, `idUsuario`, `idServicio`)  COMMENT '',
  INDEX `fk_Calificacion_Usuario1_idx` (`idUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Calificacion_EstablecimientoServicio1`
    FOREIGN KEY (`idServicio` , `idEstablecimiento`)
    REFERENCES `OutGuat`.`EstablecimientoServicio` (`idServicio` , `idEstablecimiento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificacion_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `OutGuat`.`Usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`Comentario`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `OutGuat`.`Comentario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `comentario` VARCHAR(128) NULL COMMENT '',
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   ON UPDATE CURRENT_TIMESTAMP,
  `idUsuario` INT NOT NULL COMMENT '',
  `idEstablecimiento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Comentario_Usuario1_idx` (`idUsuario` ASC)  COMMENT '',
  INDEX `fk_Comentario_Establecimiento1_idx` (`idEstablecimiento` ASC)  COMMENT '',
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `OutGuat`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Establecimiento1`
    FOREIGN KEY (`idEstablecimiento`)
    REFERENCES `OutGuat`.`Establecimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OutGuat`.`Bitacora`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `OutGuat`.`Bitacora` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idUsuario` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(256) NOT NULL COMMENT '',
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
